### ISSUE TITLE
Privacy Policy and Terms of service

### ISSUE THREAD

**Issue by WaKeMaTTa** [influyentes/influyentes#13]
**TODO**
- [ ] Create the content of _Privacy Policy_
- [ ] Create the content of _Terms of service_
- [ ] Move the content of _Privacy Policy_ to the website
- [ ] Move the content of _Terms of service_ to the website
- [ ] Add links to landing page

**Comment by WaKeMaTTa** [comment]
@influyentes/others Alguien puede crear el contendido de _Políticas de Privacidad_ y _Términos de servicio_.

Gracias.
